import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const ProductSchema = new mongoose.Schema({
  name: String,
  slug: String,
  description: String,
  price: Number,
  oldPrice: Number,
  category: String,
  subcategory: String,
  brand: String,
  images: [String],
  sizes: [String],
  colors: [String],
  inStock: Boolean,
  featured: Boolean,
  badge: String,
  discount: Number,
  createdAt: { type: Date, default: Date.now }
});

const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

const products = [
  {
    name: 'Classic White T-Shirt',
    slug: 'classic-white-tshirt',
    description: 'Premium cotton white t-shirt perfect for everyday wear',
    price: 599,
    oldPrice: 899,
    category: 'men',
    subcategory: 'tshirts',
    brand: 'Urban Threads',
    images: ['/ecom-clothes-photos/IMG_3931.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Grey'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 33
  },
  {
    name: 'Casual Denim Shirt',
    slug: 'casual-denim-shirt',
    description: 'Stylish denim shirt for a casual look',
    price: 1299,
    oldPrice: 1899,
    category: 'men',
    subcategory: 'shirts',
    brand: 'Classic Elegance',
    images: ['/ecom-clothes-photos/IMG_3933.PNG'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Light Blue', 'Dark Blue'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 32
  },
  {
    name: 'Premium Cotton Polo',
    slug: 'premium-cotton-polo',
    description: 'Comfortable polo shirt for smart casual occasions',
    price: 899,
    oldPrice: 1299,
    category: 'men',
    subcategory: 'tshirts',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3934.PNG'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White', 'Black', 'Red'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 31
  },
  {
    name: 'Elegant Evening Dress',
    slug: 'elegant-evening-dress',
    description: 'Beautiful evening dress for special occasions',
    price: 2499,
    oldPrice: 3499,
    category: 'women',
    subcategory: 'dresses',
    brand: 'Elite Fashion',
    images: ['/ecom-clothes-photos/IMG_3935.PNG'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Red', 'Navy', 'Emerald'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 29
  },
  {
    name: 'Casual Summer Top',
    slug: 'casual-summer-top',
    description: 'Light and breezy top perfect for summer',
    price: 799,
    oldPrice: 1199,
    category: 'women',
    subcategory: 'tops',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3939.PNG'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Pink', 'Blue', 'Yellow'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 33
  },
  {
    name: 'Designer Blouse',
    slug: 'designer-blouse-premium',
    description: 'Elegant designer blouse with intricate details',
    price: 1499,
    oldPrice: 2199,
    category: 'women',
    subcategory: 'tops',
    brand: 'Elite Fashion',
    images: ['/ecom-clothes-photos/IMG_3940.PNG'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Cream', 'Black'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 32
  },
  {
    name: 'Formal Blazer',
    slug: 'formal-blazer-premium',
    description: 'Professional blazer for business meetings',
    price: 2999,
    oldPrice: 4299,
    category: 'men',
    subcategory: 'formal',
    brand: 'Classic Elegance',
    images: ['/ecom-clothes-photos/IMG_3941.PNG'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Grey', 'Charcoal'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 30
  },
  {
    name: 'Stylish Jacket',
    slug: 'stylish-jacket-winter',
    description: 'Warm and stylish jacket for winter',
    price: 2199,
    oldPrice: 3199,
    category: 'men',
    subcategory: 'jackets',
    brand: 'Street Culture',
    images: ['/ecom-clothes-photos/IMG_3943.PNG'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown', 'Olive'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 31
  },
  {
    name: 'Graphic Print Tee',
    slug: 'graphic-print-tee',
    description: 'Trendy graphic t-shirt with unique design',
    price: 699,
    oldPrice: 999,
    category: 'men',
    subcategory: 'tshirts',
    brand: 'Urban Threads',
    images: ['/ecom-clothes-photos/IMG_3944.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Grey'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 30
  },
  {
    name: 'Floral Summer Dress',
    slug: 'floral-summer-dress',
    description: 'Beautiful floral dress perfect for summer',
    price: 1799,
    oldPrice: 2599,
    category: 'women',
    subcategory: 'dresses',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3946.PNG'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Floral Blue', 'Floral Pink', 'Floral Yellow'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 31
  },
  {
    name: 'Casual Hoodie',
    slug: 'casual-hoodie-comfort',
    description: 'Comfortable hoodie for casual wear',
    price: 1299,
    oldPrice: 1899,
    category: 'men',
    subcategory: 'hoodies',
    brand: 'Street Culture',
    images: ['/ecom-clothes-photos/IMG_3947.PNG'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Grey', 'Navy', 'Maroon'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 32
  },
  {
    name: 'Striped Casual Shirt',
    slug: 'striped-casual-shirt',
    description: 'Classic striped shirt for casual occasions',
    price: 999,
    oldPrice: 1499,
    category: 'men',
    subcategory: 'shirts',
    brand: 'Classic Elegance',
    images: ['/ecom-clothes-photos/IMG_3948.PNG'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue Stripe', 'Red Stripe', 'Black Stripe'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 33
  },
  {
    name: 'Elegant Maxi Dress',
    slug: 'elegant-maxi-dress',
    description: 'Long flowing maxi dress for elegant occasions',
    price: 2299,
    oldPrice: 3299,
    category: 'women',
    subcategory: 'dresses',
    brand: 'Elite Fashion',
    images: ['/ecom-clothes-photos/IMG_3949.PNG'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Burgundy', 'Emerald'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 30
  },
  {
    name: 'Casual Chinos',
    slug: 'casual-chinos',
    description: 'Comfortable chinos for everyday wear',
    price: 1199,
    oldPrice: 1799,
    category: 'men',
    subcategory: 'pants',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3950.PNG'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Khaki', 'Navy', 'Black', 'Olive'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 33
  },
  {
    name: 'Denim Jeans',
    slug: 'denim-jeans-classic',
    description: 'Classic denim jeans with perfect fit',
    price: 1499,
    oldPrice: 2199,
    category: 'men',
    subcategory: 'jeans',
    brand: 'Urban Threads',
    images: ['/ecom-clothes-photos/IMG_3951.PNG'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Blue', 'Black', 'Light Blue', 'Dark Blue'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 32
  },
  {
    name: 'Printed Kurti',
    slug: 'printed-kurti',
    description: 'Traditional kurti with modern prints',
    price: 899,
    oldPrice: 1299,
    category: 'women',
    subcategory: 'ethnic',
    brand: 'Heritage Wear',
    images: ['/ecom-clothes-photos/IMG_3952.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue', 'Pink', 'Green', 'Yellow'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 31
  },
  {
    name: 'Sports Track Pants',
    slug: 'sports-track-pants',
    description: 'Comfortable track pants for sports and gym',
    price: 799,
    oldPrice: 1199,
    category: 'men',
    subcategory: 'sportswear',
    brand: 'Street Culture',
    images: ['/ecom-clothes-photos/IMG_3953.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Grey', 'Red'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 33
  },
  {
    name: 'Formal Trousers',
    slug: 'formal-trousers',
    description: 'Professional trousers for office wear',
    price: 1299,
    oldPrice: 1899,
    category: 'men',
    subcategory: 'formal',
    brand: 'Classic Elegance',
    images: ['/ecom-clothes-photos/IMG_3954.PNG'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Black', 'Navy', 'Grey', 'Charcoal'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 32
  },
  {
    name: 'Casual Shorts',
    slug: 'casual-shorts-summer',
    description: 'Comfortable shorts for summer',
    price: 699,
    oldPrice: 999,
    category: 'men',
    subcategory: 'shorts',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3955.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Khaki', 'Navy', 'Black', 'Olive'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 30
  },
  {
    name: 'Leather Jacket',
    slug: 'leather-jacket-premium',
    description: 'Premium leather jacket for style',
    price: 3999,
    oldPrice: 5999,
    category: 'men',
    subcategory: 'jackets',
    brand: 'Elite Fashion',
    images: ['/ecom-clothes-photos/IMG_3957.PNG'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Brown', 'Tan'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 33
  },
  {
    name: 'Crop Top',
    slug: 'crop-top-trendy',
    description: 'Trendy crop top for casual wear',
    price: 599,
    oldPrice: 899,
    category: 'women',
    subcategory: 'tops',
    brand: 'Urban Threads',
    images: ['/ecom-clothes-photos/IMG_3960.PNG'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Black', 'Pink', 'Blue'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 33
  },
  {
    name: 'Palazzo Pants',
    slug: 'palazzo-pants',
    description: 'Comfortable palazzo pants for all-day wear',
    price: 999,
    oldPrice: 1499,
    category: 'women',
    subcategory: 'pants',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3961.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Maroon', 'Olive'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 33
  },
  {
    name: 'Kids Cartoon T-Shirt',
    slug: 'kids-cartoon-tshirt',
    description: 'Fun cartoon t-shirt for kids',
    price: 499,
    oldPrice: 699,
    category: 'kids',
    subcategory: 'tshirts',
    brand: 'Urban Threads',
    images: ['/ecom-clothes-photos/IMG_3962.PNG'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    colors: ['Blue', 'Red', 'Yellow', 'Green'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 29
  },
  {
    name: 'Kids Denim Jacket',
    slug: 'kids-denim-jacket',
    description: 'Stylish denim jacket for kids',
    price: 1199,
    oldPrice: 1699,
    category: 'kids',
    subcategory: 'jackets',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3963.PNG'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    colors: ['Blue', 'Light Blue', 'Black'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 29
  },
  {
    name: 'Kids Party Dress',
    slug: 'kids-party-dress',
    description: 'Beautiful party dress for special occasions',
    price: 1299,
    oldPrice: 1899,
    category: 'kids',
    subcategory: 'dresses',
    brand: 'Elite Fashion',
    images: ['/ecom-clothes-photos/IMG_3965.PNG'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y'],
    colors: ['Pink', 'White', 'Blue', 'Purple'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 32
  },
  {
    name: 'Bomber Jacket',
    slug: 'bomber-jacket-stylish',
    description: 'Trendy bomber jacket for casual wear',
    price: 1999,
    oldPrice: 2999,
    category: 'men',
    subcategory: 'jackets',
    brand: 'Street Culture',
    images: ['/ecom-clothes-photos/IMG_3966.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Olive', 'Navy', 'Maroon'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 33
  },
  {
    name: 'Cardigan Sweater',
    slug: 'cardigan-sweater',
    description: 'Cozy cardigan for winter',
    price: 1499,
    oldPrice: 2199,
    category: 'women',
    subcategory: 'sweaters',
    brand: 'Classic Elegance',
    images: ['/ecom-clothes-photos/IMG_3967.PNG'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Beige', 'Grey', 'Black', 'Navy'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 32
  },
  {
    name: 'Jogger Pants',
    slug: 'jogger-pants-comfort',
    description: 'Comfortable jogger pants for casual wear',
    price: 999,
    oldPrice: 1499,
    category: 'men',
    subcategory: 'pants',
    brand: 'Street Culture',
    images: ['/ecom-clothes-photos/IMG_3968.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Grey', 'Navy', 'Olive'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 33
  },
  {
    name: 'Wrap Dress',
    slug: 'wrap-dress-elegant',
    description: 'Elegant wrap dress for any occasion',
    price: 1799,
    oldPrice: 2599,
    category: 'women',
    subcategory: 'dresses',
    brand: 'Elite Fashion',
    images: ['/ecom-clothes-photos/IMG_3969.PNG'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Red', 'Black', 'Navy', 'Floral'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 31
  },
  {
    name: 'Henley T-Shirt',
    slug: 'henley-tshirt',
    description: 'Classic henley t-shirt with buttons',
    price: 799,
    oldPrice: 1199,
    category: 'men',
    subcategory: 'tshirts',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3970.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Grey', 'Navy'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 33
  },
  {
    name: 'Pleated Skirt',
    slug: 'pleated-skirt',
    description: 'Stylish pleated skirt for formal wear',
    price: 1099,
    oldPrice: 1599,
    category: 'women',
    subcategory: 'skirts',
    brand: 'Classic Elegance',
    images: ['/ecom-clothes-photos/IMG_3971.PNG'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Grey', 'Burgundy'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 31
  },
  {
    name: 'Kids Hoodie',
    slug: 'kids-hoodie-warm',
    description: 'Warm and cozy hoodie for kids',
    price: 899,
    oldPrice: 1299,
    category: 'kids',
    subcategory: 'hoodies',
    brand: 'Urban Threads',
    images: ['/ecom-clothes-photos/IMG_3972.PNG'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    colors: ['Black', 'Grey', 'Navy', 'Red'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 31
  },
  {
    name: 'Cargo Pants',
    slug: 'cargo-pants-utility',
    description: 'Utility cargo pants with multiple pockets',
    price: 1399,
    oldPrice: 1999,
    category: 'men',
    subcategory: 'pants',
    brand: 'Street Culture',
    images: ['/ecom-clothes-photos/IMG_3973.PNG'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Khaki', 'Olive', 'Black', 'Navy'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 30
  },
  {
    name: 'Silk Blouse',
    slug: 'silk-blouse-premium',
    description: 'Premium silk blouse for elegant occasions',
    price: 1999,
    oldPrice: 2999,
    category: 'women',
    subcategory: 'tops',
    brand: 'Elite Fashion',
    images: ['/ecom-clothes-photos/IMG_3974.PNG'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Cream', 'Black', 'Navy'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 33
  },
  {
    name: 'Sweatshirt',
    slug: 'sweatshirt-casual',
    description: 'Comfortable sweatshirt for everyday wear',
    price: 1099,
    oldPrice: 1599,
    category: 'men',
    subcategory: 'hoodies',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3975.PNG'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Black', 'Navy', 'Maroon'],
    inStock: true,
    featured: true,
    badge: 'TRENDING',
    discount: 31
  },
  {
    name: 'Midi Skirt',
    slug: 'midi-skirt-elegant',
    description: 'Elegant midi skirt for office wear',
    price: 1299,
    oldPrice: 1899,
    category: 'women',
    subcategory: 'skirts',
    brand: 'Classic Elegance',
    images: ['/ecom-clothes-photos/IMG_3976.PNG'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Grey', 'Beige'],
    inStock: true,
    featured: false,
    badge: 'SALE',
    discount: 32
  },
  {
    name: 'Kids Shorts',
    slug: 'kids-shorts-summer',
    description: 'Comfortable shorts for active kids',
    price: 499,
    oldPrice: 699,
    category: 'kids',
    subcategory: 'shorts',
    brand: 'Casual Vibes',
    images: ['/ecom-clothes-photos/IMG_3977.PNG'],
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    colors: ['Blue', 'Black', 'Khaki', 'Red'],
    inStock: true,
    featured: true,
    badge: 'NEW',
    discount: 29
  }
];

async function seedRealProducts() {
  try {
    const MONGODB_URI = process.env.MONGODB_URI;
    
    if (!MONGODB_URI) {
      throw new Error('MONGODB_URI is not defined in .env.local');
    }

    await mongoose.connect(MONGODB_URI);
    console.log('✓ Connected to MongoDB');

    // Don't delete existing products, just add new ones
    console.log('✓ Adding new products...');

    await Product.insertMany(products);
    console.log(`✓ Seeded ${products.length} new products with real images`);

    await mongoose.connection.close();
    console.log('✓ Database connection closed');
    console.log('✓ Seed completed successfully!');
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
}

seedRealProducts();
